name: base
channels:
  - defaults
  - conda-forge
dependencies:
  - anaconda-anon-usage=0.7.6
  - anaconda-auth=0.15.0
  - anaconda-cli-base=0.8.2
  - annotated-doc=0.0.4
  - annotated-types=0.6.0
  - anyio=4.12.1
  - appnope=0.1.4
  - archspec=0.2.5
  - asttokens=3.0.1
  - boltons=25.0.0
  - brotlicffi=1.2.0.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.5.14
  - certifi=2026.5.20
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - click=8.4.1
  - comm=0.2.3
  - conda=26.3.2
  - conda-anaconda-telemetry=0.3.0
  - conda-anaconda-tos=0.2.2
  - conda-content-trust=0.3.2
  - conda-libmamba-solver=26.4.0
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.12.0
  - cpp-expected=1.1.0
  - cryptography=48.0.0
  - debugpy=1.8.16
  - decorator=5.2.1
  - distro=1.9.0
  - executing=2.2.1
  - fmt=12.1.0
  - frozendict=2.4.6
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - h11=0.16.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - icu=73.1
  - idna=3.18
  - ipykernel=7.2.0
  - ipython=9.14.0
  - ipython_pygments_lexers=1.1.1
  - jansson=2.14
  - jaraco.classes=3.4.0
  - jaraco.context=6.1.0
  - jaraco.functools=4.4.0
  - jedi=0.20.0
  - jsonpatch=1.33
  - jsonpointer=3.1.1
  - jupyter_client=8.9.1
  - jupyter_core=5.9.1
  - keyring=25.7.0
  - libarchive=3.8.2
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcurl=8.19.0
  - libcxx=22.1.2
  - libev=4.33
  - libexpat=2.8.1
  - libffi=3.4.8
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libiconv=1.18
  - libidn2=2.3.8
  - libintl=0.25.1
  - libintl-devel=0.25.1
  - libkrb5=1.22.1
  - libmamba=2.3.2
  - libmambapy=2.3.2
  - libmpdec=4.0.0
  - libnghttp2=1.67.1
  - libsodium=1.0.21
  - libsolv=0.7.30
  - libssh2=1.11.1
  - libunistring=1.3
  - libxml2=2.13.9
  - libzlib=1.3.2
  - lmdb=0.9.31
  - lz4-c=1.9.4
  - markdown-it-py=4.0.0
  - matplotlib-inline=0.2.1
  - mdurl=0.1.2
  - menuinst=2.5.1
  - more-itertools=11.0.2
  - msgpack-python=1.1.1
  - ncurses=6.5
  - nest-asyncio=1.5.1
  - nest-asyncio2=1.7.2
  - nlohmann_json=3.11.2
  - openssl=3.5.7
  - packaging=26.0
  - parso=0.8.7
  - pcre2=10.46
  - pexpect=4.9.0
  - pip=26.1.1
  - pkce=1.0.3
  - platformdirs=4.9.4
  - pluggy=1.6.0
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pybind11-abi=5
  - pycosat=0.6.6
  - pycparser=3.0
  - pydantic=2.13.4
  - pydantic-core=2.46.4
  - pydantic-settings=2.12.0
  - pygments=2.20.0
  - pyjwt=2.13.0
  - pysocks=1.7.1
  - python=3.14.4
  - python-dateutil=2.9.0post0
  - python-dotenv=1.2.1
  - python.app=3
  - python_abi=3.14
  - pyzmq=27.1.0
  - readchar=4.2.1
  - readline=8.3
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.34.2
  - rich=14.2.0
  - ruamel.yaml=0.18.16
  - ruamel.yaml.clib=0.2.14
  - semver=3.0.4
  - setuptools=82.0.1
  - shellingham=1.5.4
  - simdjson=3.10.1
  - six=1.17.0
  - sqlite=3.53.2
  - stack_data=0.6.3
  - tk=8.6.15
  - tomli=2.4.0
  - tomli-w=1.2.0
  - tomlkit=0.13.3
  - tornado=6.5.5
  - tqdm=4.68.2
  - traitlets=5.15.0
  - truststore=0.10.4
  - typer=0.25.1
  - typer-slim=0.20.0
  - typer-slim-standard=0.20.0
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2026b
  - urllib3=2.7.0
  - wcwidth=0.2.14
  - wheel=0.46.3
  - xz=5.8.2
  - yaml-cpp=0.8.0
  - zeromq=4.3.5
  - zlib=1.3.2
  - zstandard=0.25.0
  - zstd=1.5.7
