name: ee506
channels:
  - conda-forge
  - defaults
dependencies:
  - _python_abi3_support=1.0
  - appnope=0.1.4
  - asttokens=3.0.1
  - bzip2=1.0.8
  - ca-certificates=2026.5.20
  - comm=0.2.3
  - cpython=3.14.6
  - debugpy=1.8.21
  - decorator=5.3.1
  - executing=2.2.1
  - icu=78.3
  - ipykernel=7.3.0
  - ipython=9.14.1
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.9.1
  - jupyter_core=5.9.1
  - krb5=1.22.2
  - libcxx=22.1.7
  - libedit=3.1.20250104
  - libexpat=2.8.1
  - libffi=3.5.2
  - liblzma=5.8.3
  - liblzma-devel=5.8.3
  - libmpdec=4.0.0
  - libsodium=1.0.22
  - libsqlite=3.53.2
  - libzlib=1.3.2
  - lz4-c=1.10.0
  - matplotlib-inline=0.2.2
  - ncurses=6.6
  - nest-asyncio2=1.7.2
  - openssl=3.6.3
  - packaging=26.2
  - parso=0.8.7
  - pexpect=4.9.0
  - pip=26.1.2
  - platformdirs=4.10.0
  - prompt-toolkit=3.0.52
  - psutil=7.2.2
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.20.0
  - python=3.14.6
  - python-dateutil=2.9.0.post0
  - python-gil=3.14.6
  - python_abi=3.14
  - pyzmq=27.1.0
  - readline=8.3
  - six=1.17.0
  - sqlite=3.53.2
  - stack_data=0.6.3
  - tk=8.6.15
  - tornado=6.5.7
  - traitlets=5.15.1
  - typing_extensions=4.15.0
  - tzdata=2026b
  - wcwidth=0.8.1
  - xz=5.8.3
  - xz-gpl-tools=5.8.3
  - xz-tools=5.8.3
  - zeromq=4.3.5
  - zlib=1.3.2
  - zstd=1.5.7
  - pip:
      - aiofiles==23.2.1
      - annotated-types==0.7.0
      - anyio==3.7.1
      - click==8.4.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - fastapi==0.104.1
      - fonttools==4.63.0
      - gevent==26.5.0
      - greenlet==3.5.1
      - h11==0.16.0
      - idna==3.18
      - kiwisolver==1.5.0
      - matplotlib==3.11.0
      - numpy==2.3.0
      - paho-mqtt==1.6.1
      - pillow==12.2.0
      - pydantic==2.13.4
      - pydantic-core==2.46.4
      - pyparsing==3.3.2
      - python-multipart==0.0.6
      - sniffio==1.3.1
      - starlette==0.27.0
      - typing-inspection==0.4.2
      - uvicorn==0.24.0
      - websocket-client==1.9.0
      - websockets==16.0
      - zope-event==6.2
      - zope-interface==8.5
